Repository 33th-SOPKATHON-TEAM-APP3/SISTAR23-iOS, pull requests merged in 2023-11, with the labels that each got.

#7 [Setting] - #3 Font/Color Literals 추가
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3.xcodeproj/project.pbxproj
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Global/Literals/ColorLiterals.swift
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Global/Literals/FontLiterals.swift
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Global/Resources/Fonts/Pretendard-Bold.otf
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Global/Resources/Fonts/Pretendard-Medium.otf
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Global/Resources/Fonts/Pretendard-Regular.otf
Labels: 😼 영서, ⚙️ Setting

#12 [Add] #11 - 폰트 만들자
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Global/Literals/FontLiterals.swift
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Info.plist
Labels: 🐻‍❄️ 민재, 🎨 UI

#14 [Feat] #4 - 아카이빙 뷰 레이아웃 구성완료
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3.xcodeproj/project.pbxproj
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Application/SceneDelegate.swift
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Presentation/Archiving/Cell/ArchivingTableViewCell.swift
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Presentation/Archiving/View/ArchivingView.swift
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Presentation/Archiving/ViewController/ArchivingViewController.swift
Labels: 🐻‍❄️ 민재, ✨ Feat, 🎨 UI

#30 [Fix] #28 - 디테일 아카이빙뷰 레이아웃 일부 수정
  33th-SOPKATHON-iOS-TEAM3/33th-SOPKATHON-iOS-TEAM3/Presentation/ArchivingDetail/ViewController/ArchivingDetatilViewController.swift
Labels: 😼 영서, ⚒️ Fix
